return {}
-- return { -- Autocompletion
-- 	"hrsh7th/nvim-cmp",
-- 	event = "InsertEnter",
-- 	dependencies = {
-- 		{
-- 			"L3MON4D3/LuaSnip",
-- 			build = (function()
-- 				return "make install_jsregexp"
-- 			end)(),
-- 			dependencies = {
-- 				{
-- 					"rafamadriz/friendly-snippets",
-- 					config = function()
-- 						require("luasnip.loaders.from_vscode").lazy_load({ exclude = { "markdown", "tex" } })
-- 					end,
-- 				},
-- 			},
-- 		},
-- 		"saadparwaiz1/cmp_luasnip",
-- 		"hrsh7th/cmp-nvim-lsp",
-- 		"hrsh7th/cmp-path",
-- 		"hrsh7th/cmp-buffer",
-- 	},
-- 	config = function()
-- 		local cmp = require("cmp")
-- 		local luasnip = require("luasnip")
--
-- 		cmp.setup({
-- 			snippet = {
-- 				expand = function(args)
-- 					luasnip.lsp_expand(args.body)
-- 				end,
-- 			},
-- 			completion = { completeopt = "menu,menuone,noinsert" },
-- 			mapping = cmp.mapping.preset.insert({
-- 				["<C-n>"] = cmp.mapping.select_next_item(),
-- 				["<C-e>"] = cmp.mapping.select_prev_item(),
-- 				["<C-j>"] = cmp.mapping.scroll_docs(-4),
-- 				["<C-k>"] = cmp.mapping.scroll_docs(4),
-- 				["<c-o>"] = cmp.mapping.confirm({ select = true }),
-- 				["<C-Space>"] = cmp.mapping.complete({}),
-- 				["<C-p>"] = cmp.mapping.close({}),
-- 			}),
-- 			sources = {
-- 				{ name = "luasnip" },
-- 				{ name = "nvim_lsp" },
-- 				{ name = "path" },
-- 				{ name = "buffer" },
-- 			},
-- 			performance = { max_view_entries = 10 },
-- 		})
-- 	end,
-- }
