#!/usr/bin/env bash
monitors=$(hyprctl monitors)



if echo "$monitors" | grep -q "ULTRAGEAR"; then
    # echo "ULTRAGEAR is connected"
    hyprctl keyword monitor eDP-1,disable
    hyprctl keyword monitor HDMI-A-1,preferred,0x0,1
    hyprctl keyword monitor HDMI-A-1,transform,1
    hyprctl keyword monitor DP-1,preferred,1080x0,1
    #
    # echo "ULTRAGEAR is not connected"
fi
