#!/bin/bash

read -p "Translate from German to English (g) or from English to German (e)? " direction
read -p "What should I translate? " text

if [ "$direction" == "g" ] || [ "$direction" == "german" ]; then
    translation=$(trans de:en "$text")
elif [ "$direction" == "e" ] || [ "$direction" == "english" ]; then
    translation=$(trans en:de "$text")
else
    echo "Invalid direction provided!"
    exit 1
fi

echo -e "$translation"

read -p "Press enter to close " end
echo "$end"

